apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: api-ppteste
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: api-ppteste
  endpoints:
    - port: http
      path: /metrics
      interval: 15s

