apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-ppteste
  name: svc-api-ppteste
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: api-ppteste
  type: LoadBalancer
